intro:
  title: Our Services
  description: The Neal Management group specializes in Regulatory Compliance,
    Operational Efficiency, and Laboratory Science
list:
  service1: Quality Management and Regulatory Compliance
  service1_desc: |-
    
    * Knowledgeable in ISO 9001:2015, COLA, ISO 17025
    * Create and Perform Laboratory Audits
    * Perform Facility and Safety Audits
    * Create Quality Management System
    * Corrective Action/Preventive Action (CAPA) Management
  service2: Laboratory Consulting
  service2_desc: |-
    
    * Perform Audits against Standards and ensure Regulatory Compliance
    * Implement Medical, Technical and Business Process Improvement
    * Perform Management and Staff Training and Development
    * Perform Patient Blood Management Consulting Services
  service3: Physician Medical Practice and POL Consulting
  service3_desc: |-
    
    * Develop Medical Office operating policies and procedures
    * Assist in Medical Office management of Human Resource activities
    * Establish and maintain Medical Office Performance Management Metrics
    * Develop Infrastructure and Operations Processes and Systems
    * Design and Implement Quality Management Systems 
    * Develop Policies and Standard Operating Procedures
    * Obtain COLA accreditation
    * Support and Maintain COLA accreditation
    * Provide COLA compliance training
  body: |-
    <!--StartFragment-->

    * Knowledgeable in ISO 9001:2015, COLA, ISO 17025
    * Create and Perform Laboratory Audits
    * Perform Facility and Safety Audits
    * Create Quality Management System
    * Corrective Action/Preventive Action (CAPA) Management
    * Develop customized Training Programs

    <!--EndFragment-->
