backend:
  #name: test-repo
  name: git-gateway
  branch: main

media_folder: "/img"
public_folder: "/img"

collections:
  - name: 'Services'
    label: 'Services'
    folder: '_services/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Item', name: 'item', widget: 'string' }
      - { label: 'Number', name: 'number', widget: 'string' }
      - { label: 'Services', name: 'body', widget: 'markdown' }

  - label: "Content Editor"
    name: "edit_content"
    files:

      - label: "Click Here To Change Your Site Info Banner"
        name: "Site_Info"
        file: "_data/info.yml"
        fields:
          - label: "banner"
            name: "banner"
            widget: "object"
            fields:
              - {label: Email Address, name: email, widget: string}
              - {label: Phone Number, name: phone, widget: string}
              - {label: Free Quote, name: quote, widget: string}

      - label: "Click Here To Change Your Home Page"
        name: "box1"
        file: "_data/homepage.yml"
        fields:
          - label: "header"
            name: "header"
            widget: "object"
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subtitle, widget: string}
              - {label: Button, name: button, widget: string}
          - label: "Transparent Box"
            name: "box"
            widget: "object"
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Content, name: content, widget: text}
              - {label: Button, name: button, widget: string}



     
      - label: "Click Here To Change Your About Page"
        name: "edit_about"
        file: "/_data/about.yml"
        fields:          
          - label: "title"
            name: "main"
            widget: "object"
            fields:
              - {label: Title, name: pagetitle, widget: string}
          - label: "Big Box"
            name: "bigbox"
            widget: "object"
            fields:
              - {label: Title, name: bigbox_title, widget: string}
              - {label: Text, name: bigbox_text, widget: text}
          - label: "Bottom Box"
            name: "bottom"
            widget: "object"
            fields:
              - {label: Title, name: bottombox_title, widget: string}
              - {label: Text, name: bottombox_text, widget: text}
      - label: "Click Here To Change Your Contact Page"
        name: "edit_contact"
        file: "/_data/contact.yml"
        fields:          
          - label: "title"
            name: "header"
            widget: "object"
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subtext, widget: string}
          - label: "Button Text"
            name: "button"
            widget: "object"
            fields:
              - {label: Button Text, name: button_text, widget: string}